name: updateplots
on:
  #schedule:
  #  - cron: '00 12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Run R script
        run: Rscript 'R/ProjectionMap.R'
      - name: Commit results
        run: |
          git config --global user.email "trevor.tombe@gmail.com"
          git config --global user.name "Trevor Tombe"
          git add 'Plots/*.*' 'Files/*.*'
          git commit -m "Update All Plots" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
